### PR TITLE
Add `SSLFetchCommand`

### PR DESCRIPTION
**Pull request by TangRufus**
Why not use ansible synchronize module?

Because it only supports passwordless sudo.

Why use ansible find module?

Because the fetch module doesn't support fetching directories recursively.

Related: https://github.com/roots/trellis-cli/issues/10

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Curious what your workflow is like for this use case?

**Comment by TangRufus** [comment]
1. download the Let'sEncrypt certs from old servers
2. set Trellis SSL to manual
3. provision new servers
4. switch Trellis SSL back to Let'sEncrypt
5. reprovision

I must admit my experience with Let'sEncrypt on Trellis is limited.
I have only 1 Trellis site using Let'sEncrypt.

**Comment by swalkinshaw** [comment]
Is there a step between 3 and 4 where you copy over the old certs you downloaded with this command?

**Comment by TangRufus** [comment]
No.

To clarify (I reordered step 4 & 5 for clarity):

1. download the Let'sEncrypt certs from old servers <-- this PR
1. set Trellis SSL to manual (to use certs from step 1)
    ```yml
    ssl:
      enabled: true
      provider: manual
      cert: /path/to/my/cert/from/step/one
      key: /path/to/my/key/from/step/one
    ```
1. provision new servers (with certs from step 1 as `manual`)
1. change DNS records (new servers using old certs)
1. switch Trellis SSL back to Let'sEncrypt (no provision at this point; only re-provision **after** DNS propagation finsished)
1. reprovision new servers (when DNS propagation finsished)
1. destroy old servers


Note: This PR only does step 1.

My new servers could use the old certs without problems.

Am I missing something?

**Comment by swalkinshaw** [comment]
Nope that makes sense and I forgot that feature of specifying the manual files 😅

I wonder if there's a slightly better step to transfer the old certs to the new one 🤔 the hard part is setting the provider to `manual` i think

**Comment by TangRufus** [comment]
How about print a message (with a link to the docs) to suggest switching provider to `manual` at the end of the command?

**Comment by swalkinshaw** [comment]
Adding a better after the command would be helpful. But also putting more instructions in the command description too 👍 

Here's what I'm thinking *might* be possible (without trying it or thinking about it too much 😅)

* building off of what's already here, the CLI downloads the certs
* then it *overrides* the new `ssl` config values for `manual` via Ansible's command line `-e` option which should take precedence over defined `group_vars`
* provisions the server with only a few tags necessary
* done?

**Comment by TangRufus** [comment]
```sh-session
$ trellis ssl fetch
$ tree trellis-cli
trellis-cli
└── ssl
    └── fetch-20200216012015
        └── 111.222.333.444
            └── etc
                └── nginx
                    └── ssl
                        ├── client-4d77f9d.crt
                        └── cloudflare-origin-ca
                            ├── typist.tech.key
                            └── typist.tech.pem
```

I recommand having another command to do the migration and keep this one for those who just want to download the certs.

### Questions

### How do we get the paths to letsencrpty keys and certs?

https://github.com/roots/trellis/blob/f11a7cefbc978831d1ff6b4156298e618ff2ff80/roles/wordpress-setup/templates/wordpress-site.conf.j2#L95-L96

i.e: hjow to get `letsencrypt_cert_ids[item.key]` and/or [generate_cert_ids](https://github.com/roots/trellis/blob/52f7f6757314b92f123e2b418248b12626b777ad/roles/letsencrypt/tasks/certificates.yml#L21)

### Is downloading keys and certs from 1 of the web servers enough?

I remember Trellis' Let's Encrypt does special things when using multiple web servers (load balancers).

**Comment by swalkinshaw** [comment]
> I recommand having another command to do the migration and keep this one for those who just want to download the certs.

Yeah makes sense 👍 

> How do we get the paths to letsencrpty keys and certs?

🤔 we could just get the `*.crt` and `*.key` files?

> Is downloading keys and certs from 1 of the web servers enough?

They should never differ so one should be correct

**Pull request closed without merging**
