### PR TITLE
Upgrade to go v1.17

### PR DESCRIPTION
**Pull request by TangRufus**
- Upgrade to go v1.17 (GitHub actions and Docker)
- `go get -u ./... && go mod tidy -go=1.17`

### CODE REVIEW

**Comment by swalkinshaw** [comment]
🎉 thanks

**Comment by swalkinshaw** [comment]
@TangRufus do we need to publish the new docker image?

**Comment by swalkinshaw** [comment]
Published new tag 🤔  still failing on a new PR

**Comment by TangRufus** [comment]
Yes, we need to publish new docker image because of https://github.com/roots/trellis-cli/blob/313af4b7db88ddec7030a8f8ce88e09d3e05e2cb/.github/workflows/ci.yml#L53

**Comment by swalkinshaw** [comment]
I published a new version, which GitHub seems to download, but its still 1.16: https://github.com/roots/trellis-cli/runs/5433873646?check_suite_focus=true

I env tried with an explicit `ENV GOLANG_VERSION=1.17` 🤔

**Comment by swalkinshaw** [comment]
I think I finally got it updated after a lot of trial and error. Honestly not sure what was going on but any changes I pushed didn't seem to take affect.

Though now some tests are failing: https://github.com/roots/trellis-cli/runs/5435266133?check_suite_focus=true

**Comment by swalkinshaw** [comment]
Ah, since Trellis was finally updated in the image (from Feb 2021), it now requires Python 3. I'll update that

**Pull request merged**
